### ISSUE TITLE
Deprecations for 2021.1

### ISSUE THREAD

**Issue by seanbudd** [nvaccess/nvda#12123]
A ticket to manage and track the code removal for upcoming deprecations in the 2021.1 release

- [x] https://github.com/nvaccess/nvda/pull/11782 (API breaking change)
```markdown
- 'NVDAObject' (and derivatives) property 'isCurrent' now strictly returns 'controlTypes.IsCurrent'. It is no longer Optional, and thus will not return None. When an object is not current 'controlTypes.IsCurrent.NO' is returned. (#11782)
- The 'controlTypes.isCurrentLabels' has been removed, instead use the 'displayString' property on a 'controlTypes.IsCurrent' enum value. EG 'controlTypes.IsCurrent.YES.displayString' (#11782)
```

- [x] https://github.com/nvaccess/nvda/pull/11639 (API breaking change)
```markdown
- `LiveText._getTextLines` has been removed. Instead, override `_getText` which returns a string of all text in the object. (#11639)
- `LiveText` objects can now calculate diffs by character. To forcibly modify this for a particular object, override the `diffAlgo` property (see the docstring for details). (#11639)
```

- [x] https://github.com/nvaccess/nvda/pull/10703 (work done in https://github.com/nvaccess/nvda/pull/11969)
```markdown
- Module level  `REASON_*` constants are removed from `controlTypes` - please use `controlTypes.OutputReason` instead. (#11969)
- `REASON_QUICKNAV` has been removed from `browseMode` - use `controlTypes.OutputReason.QUICKNAV` instead. (#11969)
```

- [x] https://github.com/nvaccess/nvda/pull/10493 (work done in: https://github.com/nvaccess/nvda/pull/11935)
```markdown
- The following functions are removed from the config module (#11935): 
   - `canStartOnSecureScreens` - use `config.isInstalledCopy` instead.
   - `hasUiAccess` and `execElevated` - use them from the `systemUtils` module.
   - `getConfigDirs` - use `globalVars.appArgs.configPath` instead
```

- [x] https://github.com/nvaccess/nvda/pull/7949 (work done in https://github.com/nvaccess/nvda/pull/12139)
```markdown
 - `winKernel.GetTimeFormat` has been removed - use `winKernel.GetTimeFormatEx` instead (#12139)
 - `winKernel.GetDateFormat` has been removed - use `winKernel.GetDateFormatEx` instead (#12139)
 ```

- [x] https://github.com/nvaccess/nvda/commit/e8f8a898772892623080a2b189b12f0ebe11fc88 (work done in https://github.com/nvaccess/nvda/pull/12144)
```markdown
- `gui.DriverSettingsMixin` has been removed - use `gui.AutoSettingsMixin` (#12144)
```

- [x] https://github.com/nvaccess/nvda/pull/10593 (work done in #12145)
```markdown
- `speech.getSpeechForSpelling` has been removed - use `speech.getSpellingSpeech` (#12145)
```

- [x] https://github.com/nvaccess/nvda/pull/11049, https://github.com/nvaccess/nvda/pull/10371, https://github.com/nvaccess/nvda/pull/10885 (work done in https://github.com/nvaccess/nvda/pull/12126)
```markdown
- Commands cannot be directly imported from speech as `import speech; speech.ExampleCommand()` or `import speech.manager; speech.manager.ExampleCommand()` - use  `from speech.commands import ExampleCommand` instead (#12126)
```

- [x] https://github.com/nvaccess/nvda/pull/10878 (work done in #12150)
```markdown
- `speakTextInfo` will no longer send speech through `speakWithoutPauses` if reason is `SAYALL`, as `sayAllhandler` does this manually now. (#12150)
```

- [x] https://github.com/nvaccess/nvda/pull/11510 (work done in #12157)
```markdown
- Support of `TextInfo`s that do not inherit from `contentRecog.BaseContentRecogTextInfo` is removed (#12157)
```

- [x] https://github.com/nvaccess/nvda/commit/4fd4fb4470e50e4369614a0ebb8fb6d637953a2c (work done in #12164)
```markdown
- `ROLE_EQUATION` has been removed from controlTypes - use `ROLE_MATH` instead (#12164)
```

- [x]  #10082 (work done in #12168)
```markdown
- `driverSetting` classes are removed from `driverHandler` - please use them from `autoSettingUtils` (#12168)
```

- [x] https://github.com/nvaccess/nvda/pull/12172 (breaking change)
```markdown
- the `synthDriverHandler` module is no longer star imported into `globalCommands` and `gui.settingsDialogs`  - use `from synthDriverHandler import synthFunctionExample` instead. (#12172)
```

- [x] #10593 (work done in #12195)
```markdown
- `speech.speakWithoutPauses` has been removed - please use `speech.SpeechWithoutPauses(speakFunc=speech.speak).speakWithoutPauses` instead. (#12195)
- `speech.re_last_pause` has been removed - please use `speech.SpeechWithoutPauses.re_last_pause` instead. (#12195)
```

- [x] #12105 (breaking change)
```markdown 
- `WelcomeDialog`, `LauncherDialog` and `AskAllowUsageStatsDialog` are moved to the `gui.startupDialogs` (#12105)
- `getDocFilePath` has been moved from `gui` to the `documentationUtils` module. (#12105)
```

- [x]  #10934  (work done in #12232)
```markdown 
- IAccessibleHandler no longer star imports everything from IAccessible and IA2 COM interfaces - please use them directly.
```

**Comment by lukaszgo1** [comment]
>     * [x]  #10703, #10732 (work done in #11969)


#10732 has not been fixed yet. #11969 only removed code marked as deprecated in #10703.

**Comment by seanbudd** [comment]
Thanks @lukaszgo1, I think I misread something

**Comment by codeofdusk** [comment]
@seanbudd Just curious, do you have any relationship to NV Access?

**Comment by lukaszgo1** [comment]
I've grepped the sources for "backwards compat" in addition to "deprec" and it turns out there are a few more places which come up. 
- Deprecated `ROLE_EQUATION` from 4fd4fb4 - I've created #12164 to remove it.
- Various imports were kept for backwards compatibility in the `driverHandler` - they were introduced by #10082 - I've created #12168 to clean them up.



There are two more which are in my view worth discussing:

- PR #10934 refactored `IAccessibleHander` - this necessitated importing various stuff just to preserve backwards compat - can these be cleaned up?
- In PR #10593 @feerrenrut created `speakWithoutPauses` as an alias for  `_speakWithoutPauses.speakWithoutPauses` and `re_last_pause` as an alias for  `_speakWithoutPauses.re_last_pause`. @feerrenrut What you intended to do with these? On the one hand 
there are according to comments kept for backwards compatibility but on the other they're pointing to the private classes inside speech.

**Comment by feerrenrut** [comment]
Thanks @lukaszgo1. Yes, these alias's with comments "kept for backwards compatibility" should be removed.

**Comment by seanbudd** [comment]
I saw Issue #10916 and PR #12105 as other ones worth discussing/adding to this list of deprecations/breaking changes.

**Comment by seanbudd** [comment]
> There are two more which are in my view worth discussing:
> 
> * PR #10934 refactored `IAccessibleHander` - this necessitated importing various stuff just to preserve backwards compat - can these be cleaned up?
> * In PR #10593 @feerrenrut created `speakWithoutPauses` as an alias for  `_speakWithoutPauses.speakWithoutPauses` and `re_last_pause` as an alias for  `_speakWithoutPauses.re_last_pause`. @feerrenrut What you intended to do with these? On the one hand there are according to comments kept for backwards compatibility but on the other they're pointing to the private classes inside speech.

@lukaszgo1 Given Reef's clarification, were you looking at fixing these? Happy to pick them up if not.

**Comment by lukaszgo1** [comment]
I'll look into them either later today or during the weekend.

**Comment by seanbudd** [comment]
I'm going to start on removing the backwards compatibility introduced in #10934 tomorrow, if you haven't already started on it

**Comment by lukaszgo1** [comment]
> 
> 
> I'm going to start on removing the backwards compatibility introduced in #10934 tomorrow, if you haven't already started on it



I've written most of the code already - it is available in ` IAccessibleHandlerNoStarImportsForCOMInterfaces` on my fork. I'll finish it off as soon as I can.
