### ISSUE TITLE
Remove internal usage of deprecated controlTypes constants

### ISSUE THREAD

**Issue by seanbudd** [nvaccess/nvda#12549]
In #12510 several `enum`s were introduced to replace constants. The usage of those constants was deprecated, the constants will be removed in 2022.1. Before the 2022.1 release process starts, the usages of the constants must be converted to use the enums instead.

- [x] `ROLE_*` constants should be replaced to their equivalent `Role.*` before 2022.1. (caused by #12510, work done by #12649)
- [x] `STATE_*` constants should be replaced to their equivalent `State.*` before 2022.1. (caused by #12510, fixed by #12712)
- [x] `roleLabels` have been deprecated, usages such as `roleLabels[ROLE_*]` should be replaced to their equivalent `Role.*.displayString` before 2022.1. (#12510, fixed by #12814)
- [x] `stateLabels` have been deprecated, usages such as `stateLabels[STATE_*]` should be replaced to their equivalent `State.*.displayString` before 2022.1. (#12510, fixed by #12821)
- [ ] `characterProcessing.SYMLVL_*` constants should be replaced using their equivalent `SymbolLevel.*` before 2022.1. (#11856)

**Comment by feerrenrut** [comment]
This has to be completed before 2022.1 is started (milestones are usually used to signify "before completion"). These changes should be started early, ideally considering this work for every release until it is complete.

**Comment by feerrenrut** [comment]
Since this code will become part of the 2021.2 API. It needs to be proved before release. If there are currently no usages of the new `enum` approach, it is yet to be proved.

**Comment by feerrenrut** [comment]
Bumping this to 2022.1. However it is important to get this done early in the dev cycle, marking as high priority. Additionally, when updating the version, the "auto deprecations" for the remaining work will need be disabled.
